# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hrbbzNXzpb-_1CurzD7mzSkgieCvDP6j
"""

import pandas as pd
import numpy as np
import streamlit as st

st.set_page_config(page_title="Market Entry Decision Agent", layout="centered")

st.title("Market Entry Decision Agent")
st.caption("Agentic decision prototype: score + rank markets with transparent weights and explanations.")

# Load data
@st.cache_data
def load_data():
    return pd.read_csv("market.csv")

df = load_data()

st.subheader("1) Business goal")
goal = st.text_input("Goal", "Choose the best market to enter next for a fintech expansion")

st.subheader("2) Set weights (importance)")
st.write("Higher weight means the factor matters more. Weights are normalized automatically.")

w_market_size = st.slider("Market size", 0, 10, 4)
w_digital = st.slider("Digital adoption", 0, 10, 3)
w_regulation = st.slider("Regulation", 0, 10, 2)
w_competition = st.slider("Competition (lower is better)", 0, 10, 1)

weights_raw = {
    "market_size": w_market_size,
    "digital_adoption": w_digital,
    "regulation": w_regulation,
    "competition": w_competition,
}

if sum(weights_raw.values()) == 0:
    st.error("Please set at least one weight > 0.")
    st.stop()

# Normalize weights
total = sum(weights_raw.values())
weights = {k: v / total for k, v in weights_raw.items()}

st.write("Normalized weights:", weights)

st.subheader("3) Rank markets")
features = list(weights.keys())
X = df[features].copy()

# Normalize feature data
X_norm = (X - X.min()) / (X.max() - X.min())

# Invert competition (lower competition -> higher score)
X_adj = X_norm.copy()
X_adj["competition"] = 1 - X_adj["competition"]

# Score
score = np.zeros(len(df))
for k, w in weights.items():
    score += X_adj[k].values * w

out = df.copy()
out["score"] = score
out = out.sort_values("score", ascending=False).reset_index(drop=True)

# Explanation
def explain_row(row):
    parts = []
    if row["digital_adoption"] >= df["digital_adoption"].median():
        parts.append("strong digital adoption")
    if row["market_size"] >= df["market_size"].median():
        parts.append("large market opportunity")
    if row["regulation"] >= df["regulation"].median():
        parts.append("more favorable regulation")
    if row["competition"] <= df["competition"].median():
        parts.append("lower competitive pressure")

    reason = ", ".join(parts) if parts else "a balanced overall profile"
    return f"{row['market']} ranks well due to {reason}."

out["explanation"] = out.apply(explain_row, axis=1)

st.success(f"Top recommendation: **{out.loc[0, 'market']}** (score: {out.loc[0, 'score']:.3f})")
st.write("Why:", out.loc[0, "explanation"])

st.dataframe(out[["market", "score", "explanation"]], use_container_width=True)

st.subheader("4) Notes (what makes it agentic)")
st.write(
    "- Takes a goal\n"
    "- Evaluates markets using multiple signals\n"
    "- Produces a ranked recommendation with transparent weights\n"
    "- Explains the decision in plain language"
)